In [27]:
import tensorflow as tf

In [ ]:
tf.reset_default_graph()

In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(x))
    sess.close()


5


In [10]:
#import tensorflow as tf
#Tensorflow Constant
#tf.constant(
#     value,    == shape
#     dtype=None,  ==type of constant
#     shape=None,  == 
#     name='Const',
#     verify_shape=False
# )


a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')

In [6]:
with tf.Session() as sess:
    print(b)
    sess.close()

Tensor("b_1:0", shape=(2, 2), dtype=int32)


In [12]:
#constant with math
# [a0*b[0] a1*b[1]] = [2*0, 1*2]
#                     [2*2, 1*3]
a = tf.constant([2, 1], name='a')
b = tf.constant([[0, 2], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')
with tf.Session() as sess:
    print(sess.run(x))
    sess.close()


[[0 2]
 [4 3]]


In [13]:
#create tensor with specific value
#tf.zeros(shape, dtype=tf.float32, name=None)

tf.zeros([2, 3], tf.int32)

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [14]:
#create a tensor 2x2 with all element = 0
tf.zeros_like([2,2])

<tf.Tensor 'zeros_like:0' shape=(2,) dtype=int32>

In [15]:
# tensor 2x2 ele = 1
tf.ones_like([2,2])

<tf.Tensor 'ones_like:0' shape=(2,) dtype=int32>

In [16]:
#create tensor 2x3 with ele = 8
tf.fill([2, 3], 8)

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

In [17]:
#tf.lin_space(start, stop, num, name=None) 
tf.lin_space(10.0, 13.0, 4) #==> [10. 11. 12. 13.]

#tf.range(start, limit=None, delta=1, dtype=None, name='range')
tf.range(3, 18, 3) #==> [3 6 9 12 15]   (start, stop, step)
tf.range(5) #==> [0 1 2 3 4]    (start = 0 (default), stop = 5, step = 1 (default))

<tf.Tensor 'range_1:0' shape=(5,) dtype=int32>

# All random function
tf.random_normal
tf.truncated_normal
tf.random_uniform
tf.random_shuffle
tf.random_crop
tf.multinomial
tf.random_gamma


# Arithmetic Ops
tf.abs
tf.negative
tf.sign
tf.reciprocal
tf.square
tf.round
tf.sqrt
tf.rsqrt
tf.pow
tf.exp


In [18]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))             #⇒ [[0 0] [1 1]]
    print(sess.run(tf.divide(b, a)))          #⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.truediv(b, a)))         #⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.floordiv(b, a)))        #⇒ [[0 0] [1 1]]
    #print(sess.run(tf.realdiv(b, a)))         #⇒ # Error: only works for real values
    print(sess.run(tf.truncatediv(b, a)))     #⇒ [[0 0] [1 1]]
    print(sess.run(tf.floor_div(b, a)))       #⇒ [[0 0] [1 1]]
    sess.close()


[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


In [20]:
#tensorflow vs numpy
import numpy as np
tf.int32 == np.int32

True

In [21]:
#Can pass numpy types to TensorFlow ops
tf.ones([2, 2], np.float32)     # ⇒ [[1.0 1.0], [1.0 1.0]]

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [22]:
sess = tf.Session()
a = tf.zeros([2, 3], np.int32)
print(type(a))              # ⇒ <class 'tensorflow.python.framework.ops.Tensor'>
a = sess.run(a)
print(type(a))              # ⇒ <class 'numpy.ndarray'>
sess.close()

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


 
two method below give the same result
tf.constant is an op
tf.Variable is a class with many ops


In [23]:
# create variables with tf.Variable
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))


In [24]:
# create variables with tf.get_variable
s1 = tf.get_variable("scalar", initializer=tf.constant(2)) 
m1 = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W1 = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [ ]:
with tf.Session() as sess:
    sess.run(tf.variables_initializer([a, b]))


In [ ]:
#Initialize a single variable
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)


In [28]:
# W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([10, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)


<tf.Variable 'Variable_1:0' shape=(10, 10) dtype=float32_ref>


In [29]:
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())     #like print(sess.run(W))

[[-0.04076865 -0.06467562  0.6722531  -0.95927244 -0.11348961  0.50543284
   0.88175917 -0.46239674 -1.6288462   0.60764724]
 [-0.4129798   1.0298625   0.2376672   0.947171    1.3080615   0.01097945
   1.0220386  -1.5582067   0.04460186 -0.14668053]
 [-0.7620799  -0.5471253  -0.33162788 -0.9302918   0.31242633  1.774834
  -0.27860847 -0.77647245  1.1060969  -0.22059426]
 [ 1.6192287   0.04366938  0.12716049 -1.236693    0.21034186 -0.08792825
   1.1052595  -0.85037166 -0.41367528  0.1084168 ]
 [-1.8653889  -1.3048458   0.18402399  1.0897834  -0.91004556  0.45649076
   0.23101546  1.1582192  -0.8451881  -0.4093021 ]
 [-0.7642775   0.40276858  1.6099849   1.5514262   0.26404226 -0.04190308
  -0.4573067   0.4697642  -0.47149405  0.15440065]
 [ 0.18363222 -0.7886365   1.3476125   1.0987529   1.5731632  -0.2996814
  -1.4621017   0.4984555  -0.08082598 -1.2740017 ]
 [ 1.5957814  -0.9443772  -0.3574294   1.9751849   0.69469064  0.25970593
   1.4844391   0.09589912 -0.8530717  -1.3453654 ]
 [-

In [30]:
# tf.Variable.assign()
# This operation outputs a Tensor that holds the new value of 'ref' after the value has been assigned
# assign() creates an assign op.
# That op needs to be executed in a session to take effect
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval())


100


In [31]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var") 

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)

#beside we have two options is assign_add() and assign_sub()


In [32]:
#EEach session maintains its own copy of variables
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))         # >> 20
print(sess2.run(W.assign_sub(2)))         # >> 8


20
8


In [33]:
sess1.close()
sess2.close()


In [36]:
#Control Dependencies
#A TF program often has 2 phases: 
#    1. Assemble a graph 
#    2. Use a session to execute operations in the graph.
#Assemble the graph first without knowing the values needed for computation

#Analogy:
#Define the function f(x, y) = 2 * x + y without knowing value of x or y. 
#x, y are placeholders for the actual values
#placeholders help us for updating data in the future