In [27]:
import tensorflow as tf

In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(x))
    sess.close()


5


In [10]:
#import tensorflow as tf
#Tensorflow Constant
#tf.constant(
#     value,    == shape
#     dtype=None,  ==type of constant
#     shape=None,  == 
#     name='Const',
#     verify_shape=False
# )


a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')

In [6]:
with tf.Session() as sess:
    print(b)
    sess.close()

Tensor("b_1:0", shape=(2, 2), dtype=int32)


In [12]:
#constant with math
# [a0*b[0] a1*b[1]] = [2*0, 1*2]
#                     [2*2, 1*3]
a = tf.constant([2, 1], name='a')
b = tf.constant([[0, 2], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')
with tf.Session() as sess:
    print(sess.run(x))
    sess.close()


[[0 2]
 [4 3]]


In [13]:
#create tensor with specific value
#tf.zeros(shape, dtype=tf.float32, name=None)

tf.zeros([2, 3], tf.int32)

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [14]:
#create a tensor 2x2 with all element = 0
tf.zeros_like([2,2])

<tf.Tensor 'zeros_like:0' shape=(2,) dtype=int32>

In [15]:
# tensor 2x2 ele = 1
tf.ones_like([2,2])

<tf.Tensor 'ones_like:0' shape=(2,) dtype=int32>

In [16]:
#create tensor 2x3 with ele = 8
tf.fill([2, 3], 8)

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

In [17]:
#tf.lin_space(start, stop, num, name=None) 
tf.lin_space(10.0, 13.0, 4) #==> [10. 11. 12. 13.]

#tf.range(start, limit=None, delta=1, dtype=None, name='range')
tf.range(3, 18, 3) #==> [3 6 9 12 15]   (start, stop, step)
tf.range(5) #==> [0 1 2 3 4]    (start = 0 (default), stop = 5, step = 1 (default))

<tf.Tensor 'range_1:0' shape=(5,) dtype=int32>

# All random function
tf.random_normal
tf.truncated_normal
tf.random_uniform
tf.random_shuffle
tf.random_crop
tf.multinomial
tf.random_gamma


# Arithmetic Ops
tf.abs
tf.negative
tf.sign
tf.reciprocal
tf.square
tf.round
tf.sqrt
tf.rsqrt
tf.pow
tf.exp


In [18]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))             #⇒ [[0 0] [1 1]]
    print(sess.run(tf.divide(b, a)))          #⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.truediv(b, a)))         #⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.floordiv(b, a)))        #⇒ [[0 0] [1 1]]
    #print(sess.run(tf.realdiv(b, a)))         #⇒ # Error: only works for real values
    print(sess.run(tf.truncatediv(b, a)))     #⇒ [[0 0] [1 1]]
    print(sess.run(tf.floor_div(b, a)))       #⇒ [[0 0] [1 1]]
    sess.close()


[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


In [20]:
#tensorflow vs numpy
import numpy as np
tf.int32 == np.int32

True

In [21]:
#Can pass numpy types to TensorFlow ops
tf.ones([2, 2], np.float32)     # ⇒ [[1.0 1.0], [1.0 1.0]]

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [22]:
sess = tf.Session()
a = tf.zeros([2, 3], np.int32)
print(type(a))              # ⇒ <class 'tensorflow.python.framework.ops.Tensor'>
a = sess.run(a)
print(type(a))              # ⇒ <class 'numpy.ndarray'>
sess.close()

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


# 
two method below give the same result
tf.constant is an op
tf.Variable is a class with many ops


In [23]:
# create variables with tf.Variable
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))


In [24]:
# create variables with tf.get_variable
s1 = tf.get_variable("scalar", initializer=tf.constant(2)) 
m1 = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W1 = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [ ]:
with tf.Session() as sess:
    sess.run(tf.variables_initializer([a, b]))


In [ ]:
#Initialize a single variable
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
